'use strict';

const fs   = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '../data/snipeSeen.txt');

// Every username ever generated by the sniper, across all sessions and
// restarts, so the generator never checks — let alone finds — the same
// username twice.
function loadSeen() {
    try {
        const content = fs.readFileSync(FILE, 'utf8');
        return new Set(content.split('\n').map(s => s.trim()).filter(Boolean));
    } catch {
        return new Set();
    }
}

function appendSeen(username) {
    const dir = path.dirname(FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(FILE, username + '\n', 'utf8');
}

module.exports = { loadSeen, appendSeen };
